[pytest]
filterwarnings =
    error
    ignore::DeprecationWarning:aifc
    ignore::DeprecationWarning:speech_recognition
    ignore::UserWarning:langchain_core
    ignore::scipy.stats.ConstantInputWarning
