#!/usr/bin/env python3
"""Generate SESSION_STATE.md for next session fast-resume."""
import os, json, datetime

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    mem_dir = os.path.dirname(script_dir)
    root = os.path.dirname(mem_dir)
    output = os.path.join(root, "SESSION_STATE.md")

    # Gather state
    project = os.path.basename(root)
    now = datetime.datetime.now().isoformat()

    # Read session data
    session = {}
    session_file = os.path.join(mem_dir, "session", "current_session.json")
    if os.path.exists(session_file):
        with open(session_file, "r", encoding="utf-8") as f:
            session = json.load(f)

    # Read task state
    tasks = {}
    task_file = os.path.join(mem_dir, "tasks", "state.json")
    if os.path.exists(task_file):
        with open(task_file, "r", encoding="utf-8") as f:
            tasks = json.load(f)

    # Generate markdown
    md = f"""# SESSION_STATE — {project}

> Auto-generated by save_session_state.py at {now}
> Read this file at the start of a new session to resume context.

## Session Info

- **Session ID**: {session.get('session_id', 'N/A')}
- **Started**: {session.get('started', 'N/A')}
- **Ticks**: {session.get('tick_count', 0)}
- **Checkpoints**: {len(session.get('checkpoints', []))}

## Active Task

- **Task**: {tasks.get('active_task', 'None')}
- **Goals**: {json.dumps(tasks.get('current_goals', []))}

## Quick Resume

1. Read this file
2. Run `/memory:refresh` to load full context
3. Continue from where you left off
"""
    with open(output, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"SESSION_STATE.md saved -> {output}")

if __name__ == "__main__":
    main()
